name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Latest Ngrok
      run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"

    - name: Extract Ngrok
      run: Expand-Archive -Path "ngrok.zip" -DestinationPath "ngrok"
      
    - name: Check Ngrok Version
      run: .\ngrok\ngrok.exe version

    - name: Authenticate Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop Services
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create Local User (For Self-Hosted Runner Only)
      run: |
        $user = Get-LocalUser -Name "zrdpadmin" -ErrorAction SilentlyContinue
        if ($null -eq $user) {
          New-LocalUser -Name "zrdpadmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force) -Description "RDP Admin"
        }
      shell: pwsh

    - name: Create Tunnel with Ngrok
      run: .\ngrok\ngrok.exe tcp 3389
